--LISTANDO TODOS OS USUÁRIOS
SELECT * FROM Usuarios

--LISTANDO TODOS OS ESTÚDIOS
SELECT * FROM Estudios

--LISTANDO TODOS OS JOGOS
SELECT * FROM Jogos

--LISTANDO TODOS OS JOGOS E SEUS RESPECTIVOS ESTÚDIOS
SELECT NomeEstudio, NomeJogo
FROM Jogos
INNER JOIN Estudios
ON Jogos.Fk_Estudio = Estudios.Id_Estudio

--BUSCAR TODOS OS ESTUDIOS(INDEPENDENTE DE HAVER JOGO OU NÃO) COM SEUS RESPECTIVOS JOGOS
SELECT NomeEstudio, NomeJogo
FROM Estudios
LEFT OUTER JOIN Jogos
ON Jogos.Fk_Estudio = Estudios.Id_Estudio
--BUSCANDO O USUARIO POR EMAIL E SENHA
SELECT * FROM Usuarios
WHERE Email = 'admin@admin.com' AND Senha = 'admin'
--BUSCANDO UM NOME POR ID ESTÚDIO
SELECT NomeEstudio FROM Estudios
WHERE Id_Estudio = 3

--BUSCAR UM JOGO POR ID JOGO
SELECT * FROM Jogos
WHERE id_Jogo = 1
